[package]
name = "mirakc-timeshift-fs"
version = "2.1.0"
authors = ["Contributors of mirakc"]
description = "A userspace filesystem to expose timeshift records as files"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
clap = { version = "4.1.7", features = ["derive", "env"] }
fuser = { version = "0.12.0", default-features = false, features = ["abi-7-31"] }
indexmap = { version = "1.9.2", features = ["serde-1"] }
libc = "0.2.139"
mirakc-core = { path = "../mirakc-core" }
sanitize-filename = "0.4.0"
serde_json = { version = "1.0.93", features = ["preserve_order"] }
tracing = "0.1.37"

[dev-dependencies]
assert_matches = "1.5.0"

# We don't specify versions because Dependabot cannot update crates in this section.
[target.'cfg(target_os = "macos")'.dependencies]
fuser = "*"  # There is no fusermount.
