[package]
name = "mirakc-timeshift-fs"
version = "2.5.7"
authors = ["Contributors of mirakc"]
description = "A userspace filesystem to expose timeshift records as files"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
clap = { version = "4.4.11", features = ["derive", "env"] }
fuser = { version = "0.14.0", default-features = false, features = ["abi-7-31"] }
indexmap = { version = "2.1.0", features = ["serde"] }
libc = "0.2.150"
mirakc-core = { path = "../mirakc-core" }
sanitize-filename = "0.5.0"
serde_json = { version = "1.0.108", features = ["preserve_order"] }
tracing = "0.1.40"

[dev-dependencies]
assert_matches = "1.5.0"

# We don't specify versions because Dependabot cannot update crates in this section.
[target.'cfg(target_os = "macos")'.dependencies]
fuser = "*"  # There is no fusermount.
