[package]
name = "mirakc-timeshift-fs"
version = "1.0.55"
authors = ["Contributors of mirakc"]
description = "A userspace filesystem to expose timeshift records as files"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
fuser = { version = "0.11.0", default-features = false, features = ["abi-7-31"] }
indexmap = { version = "1.9.1", features = ["serde-1"] }
libc = "0.2.127"
log = "0.4.17"
mirakc-core = { path = "../mirakc-core" }
sanitize-filename = "0.4.0"
serde_json = { version = "1.0.83", features = ["preserve_order"] }
structopt = "0.3.26"

[dev-dependencies]
assert_matches = "1.5.0"

# We don't specify versions because Dependabot cannot update crates in this section.
[target.'cfg(target_os = "macos")'.dependencies]
fuser = "*"  # There is no fusermount.
