[package]
name = "mirakc-timeshift-fs"
version = "1.0.34"
authors = ["Contributors of mirakc"]
description = "A userspace filesystem to expose timeshift records as files"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
fuser = { version = "0.11.0", default-features = false, features = ["abi-7-31"] }
indexmap = { version = "1.8.0", features = ["serde-1"] }
libc = "0.2.120"
log = "0.4.14"
mirakc-core = { path = "../mirakc-core" }
sanitize-filename = "0.3.0"
serde_json = { version = "1.0.79", features = ["preserve_order"] }
structopt = "0.3.26"

[dev-dependencies]
assert_matches = "1.5.0"

[target.'cfg(target_os = "macos")'.dependencies]
fuser = "0.10.0"  # There is no fusermount.
