[package]
name = "mirakc"
version = "0.12.0"
authors = ["Masayuki Nagamachi <masnagam@gmail.com>"]
description = "A Mirakurun clone written in Rust"
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
actix = { git = "https://github.com/actix/actix.git", version = "0.10.0-alpha.3" }
actix-files = "0.2"
actix-rt = "1.0"
actix-service = "1.0"
actix-web = "2.0"
bytes = "0.5"
chrono = { version = "0.4", features = ["serde"] }
clap = "2.33"
cron = "0.6"
failure = "0.1"
futures = "0.3"
humantime = "2.0"
indexmap = { version = "1.0", features = ["serde-1"] }
libc = "0.2"
log = "0.4"
mio = "0.7"
mustache = "0.9"
num_cpus = "1.10"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
serde_yaml = "0.8"
serde_qs = "0.6"
shell-words = "1.0"
tokio = { version = "0.2", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.2"

[dev-dependencies]
actix-http = "1.0"
assert_matches = "1.3"

[profile.release]
lto = true
