[package]
name = "mirakc"
version = "1.0.24"
authors = ["Contributors of mirakc"]
description = "A Mirakurun-compatible PVR backend written in Rust"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
actix = "0.12.0"
clap = "3.0.1"
log = "0.4.14"
mirakc-core = { path = "../mirakc-core" }
serde_json = { version = "1.0.74", features = ["preserve_order"] }
