[package]
name = "mirakc"
version = "1.0.81"
authors = ["Contributors of mirakc"]
description = "A Mirakurun-compatible PVR backend written in Rust"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
actix = "0.13.0"
log = "0.4.17"
mirakc-core = { path = "../mirakc-core" }
serde_json = { version = "1.0.93", features = ["preserve_order"] }
structopt = "0.3.26"
