[package]
name = "mirakc"
version = "3.1.0-dev.0"
authors = ["Contributors of mirakc"]
description = "A Mirakurun-compatible PVR backend written in Rust"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false
build = "build.rs"

[dependencies]
actlet = { path = "../actlet" }
clap = { version = "4.4.18", features = ["derive", "env"] }
chrono = { version = "0.4.33", default-features = false, features = ["clock", "serde"] }
humantime = "2.1.0"
mirakc-core = { path = "../mirakc-core" }
serde_json = { version = "1.0.113", features = ["preserve_order"] }
tempfile = "3.9.0"
tokio = { version = "1.35.1", features = ["full"] }
tracing = "0.1.40"

[build-dependencies]
vergen = { version = "8.3.1", features = ["git", "gitcl"] }
