[package]
name = "mirakc"
version = "2.5.1"
authors = ["Contributors of mirakc"]
description = "A Mirakurun-compatible PVR backend written in Rust"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
actlet = { path = "../actlet" }
clap = { version = "4.4.7", features = ["derive", "env"] }
chrono = { version = "0.4.31", default-features = false, features = ["clock", "serde"] }
humantime = "2.1.0"
mirakc-core = { path = "../mirakc-core" }
serde_json = { version = "1.0.107", features = ["preserve_order"] }
tempfile = "3.8.0"
tokio = { version = "1.33.0", features = ["full"] }
tracing = "0.1.40"
