[package]
name = "mirakc-core"
version = "3.1.0-dev.0"
authors = ["Contributors of mirakc"]
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
actlet = { path = "../actlet" }
anyhow = "1.0.80"
async-trait = "0.1.77"
axum = { version = "0.7.4", features = ["http2"] }
axum-extra = { version = "0.9.2", features = ["typed-header"] }
bytes = "1.5.0"
chrono = { version = "0.4.34", default-features = false, features = ["clock", "serde"] }
chrono-jst = { path = "../chrono-jst" }
cron = "0.12.0"
futures = "0.3.30"
glob = "0.3.1"
http-body = "1.0.0"
http-body-util = "0.1.0"
humantime = "2.1.0"
humantime-serde = "1.1.1"
hyper = { version = "1.2.0", features = ["full"] }
hyper-util = "0.1"
indexmap = { version = "2.2.3", features = ["serde"] }
is-terminal = "0.4.12"
itertools = "0.12.1"
libc = "0.2.153"
maplit = "1.0.2"
mime = "0.3.17"
mustache = "0.9.0"
once_cell = "1.19.0"
path-dedot = "3.1.1"
reqwest = { version = "0.11.24", default-features = false, features = ["json"] }
reqwest-eventsource = "0.5.0"
serde = { version = "1.0.197", features = ["derive", "rc"] }
serde_json = { version = "1.0.114", features = ["preserve_order"] }
serde_yaml = "0.9.32"
serde_qs = "0.12.0"
shell-words = "1.1.0"
smallstr = { version = "0.3.0", features = ["serde"] }
thiserror = "1.0.57"
tokio = { version = "1.36.0", features = ["full"] }
tokio-stream = { version = "0.1.14", features = ["io-util"] }
tokio-util = { version = "0.7.10", features = ["codec", "io"] }
tower = { version = "0.4.13", default-features = false, features = ["util", "make"] }
tower-http = { version = "0.5.1", features = ["fs", "trace"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "json"] }
url = { version = "2.5.0", features = ["serde"] }
utoipa = { version = "4.2.0", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "6.0.0", features = ["axum"] }
walkdir = "2.4.0"

[dev-dependencies]
assert_matches = "1.5.0"
env_logger = "0.11.2"
mockall = "0.12.1"
static_assertions = "1.1.0"
tempfile = "3.10.0"
test-log = { version = "0.2.14", features = ["trace"] }
