[package]
name = "mirakc-core"
version = "2.0.0"
authors = ["Contributors of mirakc"]
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
actlet = { path = "../actlet" }
anyhow = "1.0.69"
async-trait = "0.1.64"
atty = "0.2.14"
axum = { version = "0.6.7", features = ["http2", "headers"] }
bytes = "1.4.0"
chrono = { version = "0.4.23", default-features = false, features = ["clock", "serde"] }
chrono-jst = { path = "../chrono-jst" }
cron = "0.12.0"
futures = "0.3.26"
glob = "0.3.1"
http-body = "0.4.5"
humantime = "2.1.0"
humantime-serde = "1.1.1"
hyper = { version = "0.14.24", features = ["full"] }
indexmap = { version = "1.9.2", features = ["serde-1"] }
itertools = "0.10.5"
libc = "0.2.139"
maplit = "1.0.2"
mime = "0.3.16"
mustache = "0.9.0"
once_cell = "1.17.1"
path-dedot = "3.0.18"
reqwest = { version = "0.11.14", default-features = false, features = ["json"] }
reqwest-eventsource = "0.4.0"
serde = { version = "1.0.152", features = ["derive", "rc"] }
serde_json = { version = "1.0.93", features = ["preserve_order"] }
serde_yaml = "0.9.17"
serde_qs = "0.11.0"
shell-words = "1.1.0"
smallstr = { version = "0.3.0", features = ["serde"] }
thiserror = "1.0.38"
tokio = { version = "1.25.0", features = ["full"] }
tokio-stream = { version = "0.1.11", features = ["io-util"] }
tokio-util = { version = "0.7.7", features = ["codec", "io"] }
tower = { version = "0.4.13", default-features = false, features = ["util", "make"] }
tower-http = { version = "0.3.5", features = ["fs", "trace"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "json"] }
url = { version = "2.3.1", features = ["serde"] }
utoipa = { version = "3.0.3", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "3.0.2", features = ["axum"] }
walkdir = "2.3.2"

[dev-dependencies]
assert_matches = "1.5.0"
axum-test-helper = "0.2.0"
mockall = "0.11.3"
static_assertions = "1.1.0"
tempfile = "3.3.0"
