[package]
name = "mirakc-core"
version = "2.5.1"
authors = ["Contributors of mirakc"]
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
actlet = { path = "../actlet" }
anyhow = "1.0.75"
async-trait = "0.1.74"
axum = { version = "0.6.20", features = ["http2", "headers"] }
bytes = "1.5.0"
chrono = { version = "0.4.31", default-features = false, features = ["clock", "serde"] }
chrono-jst = { path = "../chrono-jst" }
cron = "0.12.0"
futures = "0.3.28"
glob = "0.3.1"
http-body = "0.4.5"
humantime = "2.1.0"
humantime-serde = "1.1.1"
hyper = { version = "0.14.27", features = ["full"] }
indexmap = { version = "2.0.2", features = ["serde"] }
is-terminal = "0.4.9"
itertools = "0.11.0"
libc = "0.2.149"
maplit = "1.0.2"
mime = "0.3.17"
mustache = "0.9.0"
once_cell = "1.18.0"
path-dedot = "3.1.1"
reqwest = { version = "0.11.22", default-features = false, features = ["json"] }
reqwest-eventsource = "0.5.0"
serde = { version = "1.0.190", features = ["derive", "rc"] }
serde_json = { version = "1.0.107", features = ["preserve_order"] }
serde_yaml = "0.9.25"
serde_qs = "0.12.0"
shell-words = "1.1.0"
smallstr = { version = "0.3.0", features = ["serde"] }
thiserror = "1.0.50"
tokio = { version = "1.33.0", features = ["full"] }
tokio-stream = { version = "0.1.14", features = ["io-util"] }
tokio-util = { version = "0.7.10", features = ["codec", "io"] }
tower = { version = "0.4.13", default-features = false, features = ["util", "make"] }
tower-http = { version = "0.4.4", features = ["fs", "trace"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "json"] }
url = { version = "2.4.1", features = ["serde"] }
utoipa = { version = "4.0.0", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "4.0.0", features = ["axum"] }
walkdir = "2.4.0"

[dev-dependencies]
assert_matches = "1.5.0"
axum-test-helper = "0.3.0"
mockall = "0.11.4"
paste = "1.0.14"
static_assertions = "1.1.0"
tempfile = "3.8.1"
