[package]
name = "mirakc-core"
version = "1.0.70"
authors = ["Contributors of mirakc"]
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
actix = "0.13.0"
actix-files = "0.6.2"
actix-web = "4.2.1"
anyhow = "1.0.66"
atty = "0.2.14"
chrono = { version = "0.4.23", features = ["serde"] }
cron = "0.12.0"
fs2 = "0.4.3"
futures = "0.3.25"
http-range = "0.1.5"
humantime = "2.1.0"
indexmap = { version = "1.9.2", features = ["serde-1"] }
itertools = "0.10.5"
libc = "0.2.137"
log = "0.4.17"
maplit = "1.0.2"
mustache = "0.9.0"
num_cpus = "1.14.0"
once_cell = "1.16.0"
serde = { version = "1.0.147", features = ["derive", "rc"] }
serde_json = { version = "1.0.89", features = ["preserve_order"] }
serde_yaml = "0.8.26"
serde_qs = "0.10.1"
shell-words = "1.1.0"
thiserror = "1.0.37"
tokio = { version = "1.21.2", features = ["full"] }
tokio-stream = { version = "0.1.11", features = ["io-util"] }
tokio-util = { version = "0.7.4", features = ["io"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "json"] }

[dev-dependencies]
assert_matches = "1.5.0"
