[package]
name = "mirakc-core"
version = "1.1.0-dev.0"
authors = ["Contributors of mirakc"]
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
actlet = { path = "../actlet" }
anyhow = "1.0.66"
async-trait = "0.1.58"
atty = "0.2.14"
axum = { version = "0.6.0-rc.5", features = ["headers"] }
bytes = "1.2.1"
chrono = { version = "0.4.23", features = ["serde"] }
cron = "0.12.0"
fs2 = "0.4.3"
futures = "0.3.25"
glob = "0.3.0"
http-body = "0.4.5"
humantime = "2.1.0"
humantime-serde = "1.1.1"
hyper = { version = "0.14.23", features = ["full"] }
indexmap = { version = "1.9.2", features = ["serde-1"] }
itertools = "0.10.5"
libc = "0.2.137"
maplit = "1.0.2"
mustache = "0.9.0"
once_cell = "1.16.0"
serde = { version = "1.0.147", features = ["derive", "rc"] }
serde_json = { version = "1.0.87", features = ["preserve_order"] }
serde_yaml = "0.9.14"
serde_qs = "0.10.1"
shell-words = "1.1.0"
smallstr = { version = "0.3.0", features = ["serde"] }
thiserror = "1.0.37"
tokio = { version = "1.22.0", features = ["full"] }
tokio-stream = { version = "0.1.11", features = ["io-util"] }
tokio-util = { version = "0.7.4", features = ["codec", "io"] }
tower = { version = "0.4.13", default-features = false, features = ["util", "make"] }
tower-http = { version = "0.3.4", features = ["fs", "trace"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "json"] }

[dev-dependencies]
assert_matches = "1.5.0"
axum-test-helper = { path = "../axum-test-helper" }
static_assertions = "1.1.0"
tempfile = "3.3.0"
