[package]
name = "mirakc-core"
version = "1.0.46"
authors = ["Contributors of mirakc"]
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
actix = "0.13.0"
actix-files = "0.6.0"
actix-web = "4.0.0-rc.3"
atty = "0.2.14"
chrono = { version = "0.4.19", features = ["serde"] }
cron = "0.11.0"
failure = "0.1.8"
fs2 = "0.4.3"
futures = "0.3.21"
http-range = "0.1.5"
humantime = "2.1.0"
indexmap = { version = "1.8.2", features = ["serde-1"] }
itertools = "0.10.3"
libc = "0.2.126"
log = "0.4.17"
maplit = "1.0.2"
mustache = "0.9.0"
num_cpus = "1.13.1"
once_cell = "1.12.0"
serde = { version = "1.0.137", features = ["derive", "rc"] }
serde_json = { version = "1.0.81", features = ["preserve_order"] }
serde_yaml = "0.8.24"
serde_qs = "0.9.2"
shell-words = "1.1.0"
tokio = { version = "1.19.1", features = ["full"] }
tokio-stream = { version = "0.1.9", features = ["io-util"] }
tokio-util = { version = "0.7.2", features = ["io"] }
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.11", features = ["env-filter", "json"] }

[dev-dependencies]
assert_matches = "1.5.0"
