[package]
name = "mirakc-core"
version = "1.0.19"
authors = ["Contributors of mirakc"]
edition = "2018"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
actix = "0.12.0"
actix-files = "0.6.0-beta.9"
actix-web = "4.0.0-beta.12"
atty = "0.2.14"
chrono = { version = "0.4.19", features = ["serde"] }
cron = "0.9.0"
failure = "0.1.8"
fs2 = "0.4.3"
futures = "0.3.18"
http-range = "0.1.4"
humantime = "2.1.0"
indexmap = { version = "1.7.0", features = ["serde-1"] }
itertools = "0.10.1"
libc = "0.2.108"
log = "0.4.14"
maplit = "1.0.2"
mustache = "0.9.0"
num_cpus = "1.13.0"
once_cell = "1.8.0"
serde = { version = "1.0.130", features = ["derive", "rc"] }
serde_json = { version = "1.0.72", features = ["preserve_order"] }
serde_yaml = "0.8.21"
serde_qs = "0.8.5"
shell-words = "1.0.0"
tokio = { version = "1.14.0", features = ["full"] }
tokio-stream = { version = "0.1.8", features = ["io-util"] }
tokio-util = { version = "0.6.9", features = ["io"] }
tracing = "0.1.29"
tracing-subscriber = { version = "0.3.3", features = ["env-filter", "json"] }

[dev-dependencies]
actix-http = "3.0.0-beta.14"
assert_matches = "1.5.0"
