name: buildenv

on:
  workflow_dispatch:

env:
  DEBIAN_CODENAME: bookworm

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup QEMU user-mode emulation
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
          # See https://github.com/docker/build-push-action/issues/654#issuecomment-1285190151
          config-inline: |
            [worker.oci]
              max-parallelism = 1
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
          ./scripts/update-buildenv-images --no-cache --push ${{ env.DEBIAN_CODENAME }}
