name: ci

on:
  push:
    branches:
      - main
      - release
      - trial-*
    paths-ignore:
      - '**.md'

jobs:
  build:
    uses: ./.github/workflows/build.yml
  cross-build:
    uses: ./.github/workflows/cross-build.yml
  coverage:
    uses: ./.github/workflows/coverage.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
