name: coverage

on:
  push:
    branches:
      - main
      - release
      - trial-*
    paths-ignore:
      - '**.md'
  # Don't run this workflow on pull_request.
  # This workflow uses secrets.
  pull_request_target:
    branches:
      - main
      - release
    paths-ignore:
      - '**.md'

jobs:
  coverage:
    # Skip if this workflow is triggered by dependabot.
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@nextest
      - uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        run: >-
          cargo llvm-cov nextest --all-features --workspace
          --codecov --output-path=codecov.json
      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v4
        with:
          files: codecov.json
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
