name: pull-request

on:
  pull_request:
    branches:
      - main
      - release
    paths-ignore:
      - '**.md'

jobs:
  build:
    uses: mirakc/mirakc/.github/workflows/build.yml@main
    secrets: inherit
  cross-build:
    uses: mirakc/mirakc/.github/workflows/cross-build.yml@main
    secrets: inherit
